sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Install Google Cloud CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
# Configure SDK without the Google Cloud Auth Info  - gcloud auth activate-service-account --key-file service-account.json

# Login to Docker CLI

# Build the 'Test' version of the multi-client

# Run tests

# Test OK? run script to deploy

# Build all images, tag each one, push to Docker hub

# Apply all configs from the 'k8s' folder

# Set Google Cloud to use latest version of images
